// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"fhwpy48g55","name":"WeightGuess","description":"","endpoint":"https://fhwpy48g55.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/weight","/weight/123"]},{"id":"tfaic58wxc","name":"sampleCloudApi","description":"","endpoint":"https://tfaic58wxc.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/items","/items/123"]},{"id":"4naiuj3kj2","name":"Login","description":"","endpoint":"https://4naiuj3kj2.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/items","/items/123","/login","/login/123"]},{"id":"umsosj4ys2","name":"NameRating","description":"","endpoint":"https://umsosj4ys2.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/ideas","/ideas/123","/names","/names/123"]},{"id":"9emhgbjq7l","name":"GuessDate","description":"","endpoint":"https://9emhgbjq7l.execute-api.eu-west-2.amazonaws.com/Development","region":"eu-west-2","paths":["/date","/date/123"]}],
    'aws_cognito_identity_pool_id': 'eu-west-2:6ad127c9-bd74-420a-b254-304be26709f8',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'babyshower-hosting-mobilehub-1812485621',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd26juqetd8pk2m.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'eu-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"babyshower-mobilehub-1812485621-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"eu-west-2","hashKey":"teamId","rangeKey":"personId"},{"tableName":"babyshower-mobilehub-1812485621-NameRatings","attributes":[{"name":"username","type":"S"},{"name":"Name1","type":"N"},{"name":"Name2","type":"N"},{"name":"Name3","type":"N"},{"name":"Name4","type":"N"},{"name":"Name5","type":"N"},{"name":"Name6","type":"N"}],"indexes":[],"region":"eu-west-2","hashKey":"username"},{"tableName":"babyshower-mobilehub-1812485621-GuessDate","attributes":[{"name":"username","type":"S"},{"name":"date","type":"S"}],"indexes":[],"region":"eu-west-2","hashKey":"username"},{"tableName":"babyshower-mobilehub-1812485621-NameIdeas","attributes":[{"name":"username","type":"S"},{"name":"name","type":"S"}],"indexes":[],"region":"eu-west-2","hashKey":"username"}],
    'aws_project_id': 'b6b9ba04-51ff-4578-aa59-33d2f15f2cf0',
    'aws_project_name': 'babyshower',
    'aws_project_region': 'eu-west-2',
    'aws_resource_bucket_name': 'babyshower-deployments-mobilehub-1812485621',
    'aws_resource_name_prefix': 'babyshower-mobilehub-1812485621',
}

export default awsmobile;
